apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: starlight-sidebar-topics-dropdown
    namespace: starlight-sidebar-topics-dropdown
spec:
    rules:
        - host: starlight-sidebar-topics-dropdown.trueberryless.org
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: starlight-sidebar-topics-dropdown
                            port:
                                number: 80

    tls:
        - hosts:
              - starlight-sidebar-topics-dropdown.trueberryless.org
          secretName: starlight-sidebar-topics-dropdown
